stages:
  - test

variables:
  DJANGO_SETTINGS_MODULE: "django_backend.settings_test"

django-test-job:
  stage: test
  image: python:3.8.13-bullseye
  script:
    - cd backend/django_backend
    - pip install --no-cache-dir -r requirements.txt
    - export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
    - python manage.py makemigrations database_models
    - python manage.py migrate
    - python manage.py test
