stages:         
  - test

variables:
  IMAGE: mcr.microsoft.com/windows/servercore:ltsc2019

before_script:
  # Set up the Python environment
  - apt-get update -qy
  - apt-get install -y python3 python3-pip
  - apt install python3.11-venv -qy
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install pytest

pytest-test-job:
  stage: test    
  script:
    - cd backend
    - pytest test_trial_file.py
  image:
    name: $DOCKER_IMAGE
    entrypoint: [""]


