services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend:cached
    command: bash -c "python django_backend/manage.py runserver localhost:8000"


  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend:cached
      - /frontend/node_modules
    command: bash -c "npm start"
