version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend/src:/app/frontend/src

    depends_on:
      - backend

  backend:
    build:
      context: ./backend/django_backend
      dockerfile: Dockerfile

    ports:
      - '8000:8000'

    volumes:
      - ./backend/django_backend:/app/backend

    env_file:
      - .env

  simulation:
    build:
      context: ./simulation
      dockerfile: Dockerfile

    ports:
      - '4000:4000'

    volumes:
      - ./simulation/src:/app/simulation/src

    depends_on:
      - backend
