FROM  python:3.8.13-bullseye

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app/test

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV DJANGO_SETTINGS_MODULE=django_backend.settings_test

RUN python manage.py makemigrations database_models

RUN python manage.py migrate

CMD [ "python", "manage.py", "test", "--verbosity=2"]
