FROM  python:3.8.13-bullseye

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app/test

COPY backend/django_backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/django_backend .

COPY .env .

ENV DJANGO_SETTINGS_MODULE=django_backend.settings_test

RUN python manage.py makemigrations database_models

RUN python manage.py migrate

CMD ["sh", "-c", "coverage run --source=. --omit=*/__init__.py manage.py test --verbosity=2 && coverage report"]

